// <auto-generated />
using System;
using Fashion_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fashion_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230321103559_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("bill_Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("bill_CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_IsPayment")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Price")
                        .HasColumnType("int");

                    b.Property<string>("bill_ProductColorList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPriceList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizeList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductUnitList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductsIdList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Property<string>("category_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("category_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("category_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            category_Id = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Jordan 1"
                        },
                        new
                        {
                            category_Id = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Force 1"
                        },
                        new
                        {
                            category_Id = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Yeezy"
                        },
                        new
                        {
                            category_Id = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "NMD"
                        },
                        new
                        {
                            category_Id = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "For Her"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.Property<string>("cip_ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("cip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("cip_ColorId", "cip_ProductId");

                    b.HasIndex("cip_ProductId");

                    b.ToTable("ColorInProduct", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Property<string>("color_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("color_IdDelete")
                        .HasColumnType("bit");

                    b.Property<string>("color_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("color_Id");

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.Property<string>("comment_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment_ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comment_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("comment_Id");

                    b.HasIndex("comment_ProductId");

                    b.HasIndex("comment_UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.Property<string>("contact_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("contact_EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contact_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("emailC_Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailC_Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contact_Id");

                    b.HasIndex("contact_EmailId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Property<string>("emailC_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emailC_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("emailC_Id");

                    b.ToTable("EmailCustomer", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<int?>("product_Rate")
                        .HasColumnType("int");

                    b.Property<string>("product_ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_Sold")
                        .HasColumnType("int");

                    b.Property<string>("product_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_ViewNumber")
                        .HasColumnType("int");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "4d3ec33d-ff08-4ace-8f7e-f5c1aef7741d",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Low Elevate Low ‘Iced Lilac’ hiện đã có sẵn tại Sneaker Daily Shop, đừng bỏ lỡ cơ hội của mình nhé!",
                            product_Img1 = "img/p-1/product-1.png",
                            product_Img2 = "img/p-1/product-2.png",
                            product_Img3 = "img/p-1/product-3.png",
                            product_Img4 = "img/p-1/product-4.png",
                            product_Img5 = "img/p-1/product-5.png",
                            product_Name = " Nike Air Jordan 1 Elevate Low ‘Iced Lilac’ DH7004-501",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low ‘Iced Lilac’ DH7004-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "15ea7dd2-c0b5-4fb4-b6e2-b07c69824432",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Img1 = "img/p-2/product-1.png",
                            product_Img2 = "img/p-2/product-2.png",
                            product_Img3 = "img/p-2/product-3.png",
                            product_Img4 = "img/p-2/product-4.png",
                            product_Img5 = "img/p-2/product-5.png",
                            product_Name = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "edcbc21a-8af4-4fe5-ba0f-753b0dde7964",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Img1 = "img/p-3/product-1.png",
                            product_Img2 = "img/p-3/product-2.png",
                            product_Img3 = "img/p-3/product-3.png",
                            product_Img4 = "img/p-3/product-4.png",
                            product_Img5 = "img/p-3/product-5.png",
                            product_Name = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "9bb18b73-a8c8-4c27-ac0d-209a3e30ab59",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Img1 = "img/p-4/product-1.png",
                            product_Img2 = "img/p-4/product-2.png",
                            product_Img3 = "img/p-4/product-3.png",
                            product_Img4 = "img/p-4/product-4.png",
                            product_Img5 = "img/p-4/product-5.png",
                            product_Name = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "1d8b9963-d9ec-4af4-9ca1-b4372674a9b9",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Img1 = "img/p-5/product-1.png",
                            product_Img2 = "img/p-5/product-2.png",
                            product_Img3 = "img/p-5/product-3.png",
                            product_Img4 = "img/p-5/product-4.png",
                            product_Img5 = "img/p-5/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d73a580e-fdff-4f4b-a335-e30e27d0825a",
                            IsDelete = false,
                            product_CategoryId = "64f4b71a-b320-4837-8744-deaeeea70a84",
                            product_Description = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Img1 = "img/p-6/product-1.png",
                            product_Img2 = "img/p-6/product-2.png",
                            product_Img3 = "img/p-6/product-3.png",
                            product_Img4 = "img/p-6/product-4.png",
                            product_Img5 = "img/p-6/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "ca9576d5-003d-44f1-8e8e-9a2a53ca25b9",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Img1 = "img/p-7/product-1.png",
                            product_Img2 = "img/p-7/product-2.png",
                            product_Img3 = "img/p-7/product-3.png",
                            product_Img4 = "img/p-7/product-4.png",
                            product_Img5 = "img/p-7/product-5.png",
                            product_Name = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "3efbdac8-0e33-4035-ad16-2022b0400249",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Img1 = "img/p-8/product-1.png",
                            product_Img2 = "img/p-8/product-2.png",
                            product_Img3 = "img/p-8/product-3.png",
                            product_Img4 = "img/p-8/product-4.png",
                            product_Img5 = "img/p-8/product-5.png",
                            product_Name = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "7303bd16-631b-44fa-bfd9-4119106d7901",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Img1 = "img/p-9/product-1.png",
                            product_Img2 = "img/p-9/product-2.png",
                            product_Img3 = "img/p-9/product-3.png",
                            product_Img4 = "img/p-9/product-4.png",
                            product_Img5 = "img/p-9/product-5.png",
                            product_Name = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "163ac239-bb2c-42a6-9883-7d4d49415b28",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Img1 = "img/p-10/product-1.png",
                            product_Img2 = "img/p-10/product-2.png",
                            product_Img3 = "img/p-10/product-3.png",
                            product_Img4 = "img/p-10/product-4.png",
                            product_Img5 = "img/p-10/product-5.png",
                            product_Name = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "36e51a96-4387-4ac6-b30f-2a389191b01e",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Img1 = "img/p-11/product-1.png",
                            product_Img2 = "img/p-11/product-2.png",
                            product_Img3 = "img/p-11/product-3.png",
                            product_Img4 = "img/p-11/product-4.png",
                            product_Img5 = "img/p-11/product-5.png",
                            product_Name = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "b55a7c79-0be7-4583-be33-9fee99b7dc24",
                            IsDelete = false,
                            product_CategoryId = "a76876df-a4d1-440e-b092-0c2f7e1d69ef",
                            product_Description = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Img1 = "img/p-12/product-1.png",
                            product_Img2 = "img/p-12/product-2.png",
                            product_Img3 = "img/p-12/product-3.png",
                            product_Img4 = "img/p-12/product-4.png",
                            product_Img5 = "img/p-12/product-5.png",
                            product_Name = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "7cae7415-7e28-4dcf-973e-f5b277e0d262",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Img1 = "img/p-13/product-1.png",
                            product_Img2 = "img/p-13/product-2.png",
                            product_Img3 = "img/p-13/product-3.png",
                            product_Img4 = "img/p-13/product-4.png",
                            product_Img5 = "img/p-13/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "0b891a91-2c84-4eb9-9e75-1a81515a9c5b",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Img1 = "img/p-14/product-1.png",
                            product_Img2 = "img/p-14/product-2.png",
                            product_Img3 = "img/p-14/product-3.png",
                            product_Img4 = "img/p-14/product-4.png",
                            product_Img5 = "img/p-14/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "eb2438de-4d1f-43fa-96e8-010957ace19f",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Img1 = "img/p-15/product-1.png",
                            product_Img2 = "img/p-15/product-2.png",
                            product_Img3 = "img/p-15/product-3.png",
                            product_Img4 = "img/p-15/product-4.png",
                            product_Img5 = "img/p-15/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d87a2aa7-c2d6-4615-ac12-eba8c6ef9d4d",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Img1 = "img/p-16/product-1.png",
                            product_Img2 = "img/p-16/product-2.png",
                            product_Img3 = "img/p-16/product-3.png",
                            product_Img4 = "img/p-16/product-4.png",
                            product_Img5 = "img/p-16/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "5594f33d-e3d4-40af-88ce-c65f1eb4a4e5",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Img1 = "img/p-17/product-1.png",
                            product_Img2 = "img/p-17/product-2.png",
                            product_Img3 = "img/p-17/product-3.png",
                            product_Img4 = "img/p-17/product-4.png",
                            product_Img5 = "img/p-17/product-5.png",
                            product_Name = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "65d194ae-e655-4912-8b72-b2a43ea2251f",
                            IsDelete = false,
                            product_CategoryId = "d2e76e3d-7903-4daa-bdfa-486202f89b99",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Img1 = "img/p-18/product-1.png",
                            product_Img2 = "img/p-18/product-2.png",
                            product_Img3 = "img/p-18/product-3.png",
                            product_Img4 = "img/p-18/product-4.png",
                            product_Img5 = "img/p-18/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "65970b0d-8209-4db2-bc7a-c8db084d47b9",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Img1 = "img/p-19/product-1.png",
                            product_Img2 = "img/p-19/product-2.png",
                            product_Img3 = "img/p-19/product-3.png",
                            product_Img4 = "img/p-19/product-4.png",
                            product_Img5 = "img/p-19/product-5.png",
                            product_Name = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "dfe1f4c6-d870-4355-9342-adc329e791aa",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Img1 = "img/p-20/product-1.png",
                            product_Img2 = "img/p-20/product-2.png",
                            product_Img3 = "img/p-20/product-3.png",
                            product_Img4 = "img/p-20/product-4.png",
                            product_Img5 = "img/p-20/product-5.png",
                            product_Name = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "ecab1e75-beb2-45e9-bb29-ce132bfaa9e3",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Img1 = "img/p-21/product-1.png",
                            product_Img2 = "img/p-21/product-2.png",
                            product_Img3 = "img/p-21/product-3.png",
                            product_Img4 = "img/p-21/product-4.png",
                            product_Img5 = "img/p-21/product-5.png",
                            product_Name = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "7a2a140c-0f9b-46a2-9203-737e2d27e3a3",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Img1 = "img/p-22/product-1.png",
                            product_Img2 = "img/p-22/product-2.png",
                            product_Img3 = "img/p-22/product-3.png",
                            product_Img4 = "img/p-22/product-4.png",
                            product_Img5 = "img/p-22/product-5.png",
                            product_Name = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "17d38673-f471-42fe-98eb-b0d1d116c2b6",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Img1 = "img/p-23/product-1.png",
                            product_Img2 = "img/p-23/product-2.png",
                            product_Img3 = "img/p-23/product-3.png",
                            product_Img4 = "img/p-23/product-4.png",
                            product_Img5 = "img/p-23/product-5.png",
                            product_Name = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d0ea0f5c-029f-4c47-aa47-0825c46c5c31",
                            IsDelete = false,
                            product_CategoryId = "5e1736b4-f4fc-4305-bda1-073db92993f2",
                            product_Description = "Adidas EQ19 Run H00933",
                            product_Img1 = "img/p-24/product-1.png",
                            product_Img2 = "img/p-24/product-2.png",
                            product_Img3 = "img/p-24/product-3.png",
                            product_Img4 = "img/p-24/product-4.png",
                            product_Img5 = "img/p-24/product-5.png",
                            product_Name = "Adidas EQ19 Run H00933",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas EQ19 Run H00933",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "eeb70329-5966-43cb-8cea-15ebd039fd7f",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Img1 = "img/p-25/product-1.png",
                            product_Img2 = "img/p-25/product-2.png",
                            product_Img3 = "img/p-25/product-3.png",
                            product_Img4 = "img/p-25/product-4.png",
                            product_Img5 = "img/p-25/product-5.png",
                            product_Name = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "b637bf4a-0e4f-4427-bb71-aeaa12f810b4",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Img1 = "img/p-26/product-1.png",
                            product_Img2 = "img/p-26/product-2.png",
                            product_Img3 = "img/p-26/product-3.png",
                            product_Img4 = "img/p-26/product-4.png",
                            product_Img5 = "img/p-26/product-5.png",
                            product_Name = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d08c9183-3dd0-4503-9c0d-e4c46d43e56a",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Img1 = "img/p-27/product-1.png",
                            product_Img2 = "img/p-27/product-2.png",
                            product_Img3 = "img/p-27/product-3.png",
                            product_Img4 = "img/p-27/product-4.png",
                            product_Img5 = "img/p-27/product-5.png",
                            product_Name = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "8dc09800-40d1-4b82-a4c6-69946cb3bddf",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Img1 = "img/p-28/product-1.png",
                            product_Img2 = "img/p-28/product-2.png",
                            product_Img3 = "img/p-28/product-3.png",
                            product_Img4 = "img/p-28/product-4.png",
                            product_Img5 = "img/p-28/product-5.png",
                            product_Name = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "1e3d5e70-c075-48b0-ab30-651046e77136",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Img1 = "img/p-29/product-1.png",
                            product_Img2 = "img/p-29/product-2.png",
                            product_Img3 = "img/p-29/product-3.png",
                            product_Img4 = "img/p-29/product-4.png",
                            product_Img5 = "img/p-29/product-5.png",
                            product_Name = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d3210244-cd2e-4393-824e-e061f664eae1",
                            IsDelete = false,
                            product_CategoryId = "eb10eeeb-9656-4ceb-8a43-cb243a2fbd0c",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Img1 = "img/p-30/product-1.png",
                            product_Img2 = "img/p-30/product-2.png",
                            product_Img3 = "img/p-30/product-3.png",
                            product_Img4 = "img/p-30/product-4.png",
                            product_Img5 = "img/p-30/product-5.png",
                            product_Name = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.Property<string>("sip_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("sip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("sip_Id", "sip_ProductId");

                    b.HasIndex("sip_ProductId");

                    b.ToTable("SizeInProduct", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Property<string>("size_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("size_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("size_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("size_Id");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f934a11a-2568-48d0-9176-a24a0c469a72",
                            RoleId = "25320209-a63e-4b28-a0b4-61751e38e969"
                        },
                        new
                        {
                            UserId = "18770765-21c2-4e59-b7c2-508926eaa93a",
                            RoleId = "e2ddf888-aa93-49b9-bffe-54f7d3c59c95"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.RolesTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("RolesTable");

                    b.HasData(
                        new
                        {
                            Id = "25320209-a63e-4b28-a0b4-61751e38e969",
                            ConcurrencyStamp = "72f5641f-8386-42f4-b75b-8258c80d0a6e",
                            Name = "Admin",
                            NormalizedName = "admin",
                            IsDelete = false
                        },
                        new
                        {
                            Id = "e2ddf888-aa93-49b9-bffe-54f7d3c59c95",
                            ConcurrencyStamp = "8c550b65-0ae2-4eba-9275-aae6adaade82",
                            Name = "Staff",
                            NormalizedName = "staff",
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsersTable");

                    b.HasData(
                        new
                        {
                            Id = "f934a11a-2568-48d0-9176-a24a0c469a72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f564853-825c-47c2-8d24-0a9fff42f88d",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEInoHIaBHlYtAi7KMfAb3GrFqEOIdpM9OOP0E/p13AfbQQA38ky11i62YXv+nNCx2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f8319720-436c-4532-972d-3af948f1c2db",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        },
                        new
                        {
                            Id = "18770765-21c2-4e59-b7c2-508926eaa93a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7eaf727c-8583-4132-af78-5a5022cd99d1",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAED/ZytyCJARx/fSzcDkNmdWyzoK6zAuNIVHeIrjVmBkn8/fr9Dv8oufKPTYJaO9v2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4984e899-2d05-4ff3-b625-3eac97691147",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "userTable_UserId")
                        .WithMany("billsTablesList")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userTable_UserId");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ColorsTable", "cip_Color")
                        .WithMany("color_InProductsList")
                        .HasForeignKey("cip_ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "cip_Product")
                        .WithMany("product_colorInProductTablesList")
                        .HasForeignKey("cip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cip_Color");

                    b.Navigation("cip_Product");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "comment_ProductsTable")
                        .WithMany("product_CommentTableList")
                        .HasForeignKey("comment_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "comment_UsersTable")
                        .WithMany("CommentTableList")
                        .HasForeignKey("comment_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment_ProductsTable");

                    b.Navigation("comment_UsersTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.EmailCustomerTable", "contact_EmailCustomerTable")
                        .WithMany("emailC_ContactTableList")
                        .HasForeignKey("contact_EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contact_EmailCustomerTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.CategoriesTable", "product_CategoriesTable")
                        .WithMany("ProductsTableList")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_CategoriesTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.SizeTable", "sip_Size")
                        .WithMany("size_sizeInProductTablesList")
                        .HasForeignKey("sip_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "sip_Product")
                        .WithMany("product_sizeInProductTablesList")
                        .HasForeignKey("sip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sip_Product");

                    b.Navigation("sip_Size");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Navigation("ProductsTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Navigation("color_InProductsList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Navigation("emailC_ContactTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Navigation("product_CommentTableList");

                    b.Navigation("product_colorInProductTablesList");

                    b.Navigation("product_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Navigation("size_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.Navigation("CommentTableList");

                    b.Navigation("billsTablesList");
                });
#pragma warning restore 612, 618
        }
    }
}
