// <auto-generated />
using System;
using Fashion_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fashion_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230213172524_init9")]
    partial class init9
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bill_Code")
                        .HasColumnType("int");

                    b.Property<double>("bill_Price")
                        .HasColumnType("float");

                    b.Property<string>("bill_ProductColorList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPriceList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizeList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductUnitList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductsIdList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);

                    b.HasData(
                        new
                        {
                            bill_Id = "58f23a31-a072-4b4b-9eec-c09a5ee99cc3",
                            CreateBy = "CreateBy",
                            CreateOn = "CreateOn",
                            IsDelete = false,
                            UpdateBy = "UpdateBy",
                            UpdateOn = "UpdateOn",
                            bill_Code = 1,
                            bill_Price = 0.0,
                            bill_ProductColorList = "",
                            bill_ProductPriceList = "",
                            bill_ProductSizeList = "",
                            bill_ProductUnitList = "",
                            bill_ProductsIdList = "",
                            bill_UserId = "7742eeba-76d5-41ec-bdc1-c31304862a78"
                        },
                        new
                        {
                            bill_Id = "6f50bca8-dea2-463c-af13-f678bf6ce1e6",
                            CreateBy = "CreateBy",
                            CreateOn = "CreateOn",
                            IsDelete = false,
                            UpdateBy = "UpdateBy",
                            UpdateOn = "UpdateOn",
                            bill_Code = 1,
                            bill_Price = 0.0,
                            bill_ProductColorList = "",
                            bill_ProductPriceList = "",
                            bill_ProductSizeList = "",
                            bill_ProductUnitList = "",
                            bill_ProductsIdList = "",
                            bill_UserId = "7742eeba-76d5-41ec-bdc1-c31304862a78"
                        },
                        new
                        {
                            bill_Id = "d00c9360-fb82-4554-a6ae-3d0c32a9ea1f",
                            CreateBy = "CreateBy",
                            CreateOn = "CreateOn",
                            IsDelete = false,
                            UpdateBy = "UpdateBy",
                            UpdateOn = "UpdateOn",
                            bill_Code = 1,
                            bill_Price = 0.0,
                            bill_ProductColorList = "",
                            bill_ProductPriceList = "",
                            bill_ProductSizeList = "",
                            bill_ProductUnitList = "",
                            bill_ProductsIdList = "",
                            bill_UserId = "6018b7d5-9db3-4de7-94ac-e142f1ca862a"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Property<string>("category_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("categpry_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            category_Id = "1d78bcfe-137b-42b8-8fc6-8dcddbaa1904",
                            CreateBy = "CreateBy",
                            CreateOn = "CreateOn",
                            IsDelete = false,
                            UpdateBy = "UpdateBy",
                            UpdateOn = "UpdateOn",
                            category_Name = "category_Name",
                            categpry_Description = "category_Description"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateOn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<int?>("product_Rate")
                        .HasColumnType("int");

                    b.Property<string>("product_ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_Sold")
                        .HasColumnType("int");

                    b.Property<string>("product_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_ViewNumber")
                        .HasColumnType("int");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "046b7f5d-883c-45c6-a1ab-d5ac3afc06e6",
                            CreateBy = "CreateBy",
                            CreateOn = "CreateOn",
                            IsDelete = false,
                            UpdateBy = "UpdateBy",
                            UpdateOn = "UpdateOn",
                            product_CategoryId = "1d78bcfe-137b-42b8-8fc6-8dcddbaa1904",
                            product_Description = "Guard dog",
                            product_Img1 = "img1",
                            product_Img2 = "img2",
                            product_Img3 = "img3",
                            product_Img4 = "img4",
                            product_Img5 = "img5",
                            product_Name = "Guard dog",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Short Description",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7742eeba-76d5-41ec-bdc1-c31304862a78",
                            RoleId = "dea4d762-a23f-4cba-a038-2259193cc7da"
                        },
                        new
                        {
                            UserId = "6018b7d5-9db3-4de7-94ac-e142f1ca862a",
                            RoleId = "f12299e3-23c0-4d65-b6be-66f0293b3f1b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.RolesTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("RolesTable");

                    b.HasData(
                        new
                        {
                            Id = "dea4d762-a23f-4cba-a038-2259193cc7da",
                            ConcurrencyStamp = "f983d701-bf69-4f2f-b170-135b7aa6be8f",
                            Name = "ADMIN",
                            NormalizedName = "admin",
                            IsDelete = false
                        },
                        new
                        {
                            Id = "f12299e3-23c0-4d65-b6be-66f0293b3f1b",
                            ConcurrencyStamp = "cd22a37c-e024-4ae2-b46a-804c0ca1893c",
                            Name = "STAFF",
                            NormalizedName = "staff",
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsersTable");

                    b.HasData(
                        new
                        {
                            Id = "7742eeba-76d5-41ec-bdc1-c31304862a78",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40b73046-51c3-4f27-8299-de1c22c6df03",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEP9j1yE6I4yhq3pDni0Inl1udl+zez87W+sZQlEnz5V9pxoREX7fjDoaArHbFL28Mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b36b60a6-6d6d-4dfd-b2d3-29cfa96da326",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            Address = "",
                            FirstName = "FirstName",
                            IsDelete = false,
                            LastName = "LastName"
                        },
                        new
                        {
                            Id = "6018b7d5-9db3-4de7-94ac-e142f1ca862a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "42fa9d3b-90c3-4684-af27-1c9318e8e93e",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEAaFLIphmICD1X/ZfY68x6oYyfI+88H6o/h1BdyLjDmwp7WAM4MkpUNvaruCsYbWXg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "edc99be5-d742-4dbf-a466-42f0054fb125",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Address = "",
                            FirstName = "FirstName",
                            IsDelete = false,
                            LastName = "LastName"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "userTable_UserId")
                        .WithMany("billsTablesList")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userTable_UserId");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.CategoriesTable", "productCategoryId")
                        .WithMany("Products")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productCategoryId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.Navigation("billsTablesList");
                });
#pragma warning restore 612, 618
        }
    }
}
