// <auto-generated />
using System;
using Fashion_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fashion_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230321152433_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("bill_Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("bill_CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_IsPayment")
                        .HasColumnType("bit");

                    b.Property<int>("bill_Price")
                        .HasColumnType("int");

                    b.Property<string>("bill_ProductColorList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPriceList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizeList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductUnitList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductsIdList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Property<string>("category_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("category_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("category_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            category_Id = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Jordan 1"
                        },
                        new
                        {
                            category_Id = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Force 1"
                        },
                        new
                        {
                            category_Id = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Yeezy"
                        },
                        new
                        {
                            category_Id = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "NMD"
                        },
                        new
                        {
                            category_Id = "70384946-c313-4edf-b98a-66ed223b2168",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "For Her"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.Property<string>("cip_ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("cip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("cip_ColorId", "cip_ProductId");

                    b.HasIndex("cip_ProductId");

                    b.ToTable("ColorInProduct", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Property<string>("color_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("color_IdDelete")
                        .HasColumnType("bit");

                    b.Property<string>("color_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("color_Id");

                    b.ToTable("Color", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.Property<string>("comment_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment_ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comment_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("comment_Id");

                    b.HasIndex("comment_ProductId");

                    b.HasIndex("comment_UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.Property<string>("contact_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("contact_EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contact_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("emailC_Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailC_Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contact_Id");

                    b.HasIndex("contact_EmailId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Property<string>("emailC_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emailC_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("emailC_Id");

                    b.ToTable("EmailCustomer", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<int?>("product_Rate")
                        .HasColumnType("int");

                    b.Property<string>("product_ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_Sold")
                        .HasColumnType("int");

                    b.Property<string>("product_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_ViewNumber")
                        .HasColumnType("int");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "2fdff5bb-64a9-49b0-86a9-dddaa7c0aa1a",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Low Elevate Low ‘Iced Lilac’ hiện đã có sẵn tại Sneaker Daily Shop, đừng bỏ lỡ cơ hội của mình nhé!",
                            product_Img1 = "StaticFiles/p-1/product-1.png",
                            product_Img2 = "StaticFiles/p-1/product-2.png",
                            product_Img3 = "StaticFiles/p-1/product-3.png",
                            product_Img4 = "StaticFiles/p-1/product-4.png",
                            product_Img5 = "StaticFiles/p-1/product-5.png",
                            product_Name = " Nike Air Jordan 1 Elevate",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low ‘Iced Lilac’ DH7004-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "9f92f5b4-9005-4a27-9fbe-631c9a111c89",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Img1 = "StaticFiles/p-2/product-1.png",
                            product_Img2 = "StaticFiles/p-2/product-2.png",
                            product_Img3 = "StaticFiles/p-2/product-3.png",
                            product_Img4 = "StaticFiles/p-2/product-4.png",
                            product_Img5 = "StaticFiles/p-2/product-5.png",
                            product_Name = "Nike Air Jordan 1 Elevate",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "f3908318-4fae-4d84-b79f-7b63753de07b",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Img1 = "StaticFiles/p-3/product-1.png",
                            product_Img2 = "StaticFiles/p-3/product-2.png",
                            product_Img3 = "StaticFiles/p-3/product-3.png",
                            product_Img4 = "StaticFiles/p-3/product-4.png",
                            product_Img5 = "StaticFiles/p-3/product-5.png",
                            product_Name = "Nike Air Jordan 1 Retro",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "574b85d2-195c-4f49-a0ce-04e6de1e3beb",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Img1 = "StaticFiles/p-4/product-1.png",
                            product_Img2 = "StaticFiles/p-4/product-2.png",
                            product_Img3 = "StaticFiles/p-4/product-3.png",
                            product_Img4 = "StaticFiles/p-4/product-4.png",
                            product_Img5 = "StaticFiles/p-4/product-5.png",
                            product_Name = "Nike Air Jordan 1 Mid",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "ccdbd6e4-a134-4cdf-a2fb-c320735cc534",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Img1 = "StaticFiles/p-5/product-1.png",
                            product_Img2 = "StaticFiles/p-5/product-2.png",
                            product_Img3 = "StaticFiles/p-5/product-3.png",
                            product_Img4 = "StaticFiles/p-5/product-4.png",
                            product_Img5 = "StaticFiles/p-5/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "dec7576d-36ef-4bde-b98f-9283e1d96881",
                            IsDelete = false,
                            product_CategoryId = "bc01668e-651a-4ce5-8d3f-cce35ea7e2b2",
                            product_Description = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Img1 = "StaticFiles/p-6/product-1.png",
                            product_Img2 = "StaticFiles/p-6/product-2.png",
                            product_Img3 = "StaticFiles/p-6/product-3.png",
                            product_Img4 = "StaticFiles/p-6/product-4.png",
                            product_Img5 = "StaticFiles/p-6/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "dec0fff8-0e8c-4b43-8594-4bf86a49393c",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Img1 = "StaticFiles/p-7/product-1.png",
                            product_Img2 = "StaticFiles/p-7/product-2.png",
                            product_Img3 = "StaticFiles/p-7/product-3.png",
                            product_Img4 = "StaticFiles/p-7/product-4.png",
                            product_Img5 = "StaticFiles/p-7/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "406c5592-c009-460c-8901-5819ff1347ab",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Img1 = "StaticFiles/p-8/product-1.png",
                            product_Img2 = "StaticFiles/p-8/product-2.png",
                            product_Img3 = "StaticFiles/p-8/product-3.png",
                            product_Img4 = "StaticFiles/p-8/product-4.png",
                            product_Img5 = "StaticFiles/p-8/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "8dc1e2a3-4d9f-4810-beee-a7432cb4050b",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Img1 = "StaticFiles/p-9/product-1.png",
                            product_Img2 = "StaticFiles/p-9/product-2.png",
                            product_Img3 = "StaticFiles/p-9/product-3.png",
                            product_Img4 = "StaticFiles/p-9/product-4.png",
                            product_Img5 = "StaticFiles/p-9/product-5.png",
                            product_Name = "Nike Air Force 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "7acc888a-116d-4773-ae5f-430aa8a8354a",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Img1 = "StaticFiles/p-10/product-1.png",
                            product_Img2 = "StaticFiles/p-10/product-2.png",
                            product_Img3 = "StaticFiles/p-10/product-3.png",
                            product_Img4 = "StaticFiles/p-10/product-4.png",
                            product_Img5 = "StaticFiles/p-10/product-5.png",
                            product_Name = "Nike Air Force 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "0fa1c2ff-d765-468a-8fd5-419b4dbbdc1b",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Img1 = "StaticFiles/p-11/product-1.png",
                            product_Img2 = "StaticFiles/p-11/product-2.png",
                            product_Img3 = "StaticFiles/p-11/product-3.png",
                            product_Img4 = "StaticFiles/p-11/product-4.png",
                            product_Img5 = "StaticFiles/p-11/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "423b7b9f-07a5-4d46-80a2-c095b1c6cc5f",
                            IsDelete = false,
                            product_CategoryId = "a0d4702b-d615-40b1-ac8e-3709755fec96",
                            product_Description = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Img1 = "StaticFiles/p-12/product-1.png",
                            product_Img2 = "StaticFiles/p-12/product-2.png",
                            product_Img3 = "StaticFiles/p-12/product-3.png",
                            product_Img4 = "StaticFiles/p-12/product-4.png",
                            product_Img5 = "StaticFiles/p-12/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "0e847f0e-2c7c-41ca-a704-78536b5f8ef8",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Img1 = "StaticFiles/p-13/product-1.png",
                            product_Img2 = "StaticFiles/p-13/product-2.png",
                            product_Img3 = "StaticFiles/p-13/product-3.png",
                            product_Img4 = "StaticFiles/p-13/product-4.png",
                            product_Img5 = "StaticFiles/p-13/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "e4fe45ce-1f9e-4e32-b769-b15cb828bcfc",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Img1 = "StaticFiles/p-14/product-1.png",
                            product_Img2 = "StaticFiles/p-14/product-2.png",
                            product_Img3 = "StaticFiles/p-14/product-3.png",
                            product_Img4 = "StaticFiles/p-14/product-4.png",
                            product_Img5 = "StaticFiles/p-14/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "e3bcee6d-1992-45af-b02b-4cb0fbab41a4",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Img1 = "StaticFiles/p-15/product-1.png",
                            product_Img2 = "StaticFiles/p-15/product-2.png",
                            product_Img3 = "StaticFiles/p-15/product-3.png",
                            product_Img4 = "StaticFiles/p-15/product-4.png",
                            product_Img5 = "StaticFiles/p-15/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "54f2ba97-25e9-45fd-87ab-a736318718ce",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Img1 = "StaticFiles/p-16/product-1.png",
                            product_Img2 = "StaticFiles/p-16/product-2.png",
                            product_Img3 = "StaticFiles/p-16/product-3.png",
                            product_Img4 = "StaticFiles/p-16/product-4.png",
                            product_Img5 = "StaticFiles/p-16/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "088a0124-3569-4c1f-a896-2dde6aab9e75",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Img1 = "StaticFiles/p-17/product-1.png",
                            product_Img2 = "StaticFiles/p-17/product-2.png",
                            product_Img3 = "StaticFiles/p-17/product-3.png",
                            product_Img4 = "StaticFiles/p-17/product-4.png",
                            product_Img5 = "StaticFiles/p-17/product-5.png",
                            product_Name = "Adidas Originals Yeezy",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "c436989b-45fd-4b29-bbfe-1c2865f2af1a",
                            IsDelete = false,
                            product_CategoryId = "a871d64f-fb05-4a24-b60d-225c07575f0a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Img1 = "StaticFiles/p-18/product-1.png",
                            product_Img2 = "StaticFiles/p-18/product-2.png",
                            product_Img3 = "StaticFiles/p-18/product-3.png",
                            product_Img4 = "StaticFiles/p-18/product-4.png",
                            product_Img5 = "StaticFiles/p-18/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "8b49901b-f441-4373-b525-57b24923b65a",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Img1 = "StaticFiles/p-19/product-1.png",
                            product_Img2 = "StaticFiles/p-19/product-2.png",
                            product_Img3 = "StaticFiles/p-19/product-3.png",
                            product_Img4 = "StaticFiles/p-19/product-4.png",
                            product_Img5 = "StaticFiles/p-19/product-5.png",
                            product_Name = "Adidas NMD_R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "c5cc27f3-5092-49f4-8047-bd2aad9627d9",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Img1 = "StaticFiles/p-20/product-1.png",
                            product_Img2 = "StaticFiles/p-20/product-2.png",
                            product_Img3 = "StaticFiles/p-20/product-3.png",
                            product_Img4 = "StaticFiles/p-20/product-4.png",
                            product_Img5 = "StaticFiles/p-20/product-5.png",
                            product_Name = "Adidas BOSSK NMD_R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "44dc4584-2a09-4c38-a125-355be34ae44c",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Img1 = "StaticFiles/p-21/product-1.png",
                            product_Img2 = "StaticFiles/p-21/product-2.png",
                            product_Img3 = "StaticFiles/p-21/product-3.png",
                            product_Img4 = "StaticFiles/p-21/product-4.png",
                            product_Img5 = "StaticFiles/p-21/product-5.png",
                            product_Name = "Adidas NMD R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "13e053e3-da04-4fc0-84ad-3ebfbd42e11f",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Img1 = "StaticFiles/p-22/product-1.png",
                            product_Img2 = "StaticFiles/p-22/product-2.png",
                            product_Img3 = "StaticFiles/p-22/product-3.png",
                            product_Img4 = "StaticFiles/p-22/product-4.png",
                            product_Img5 = "StaticFiles/p-22/product-5.png",
                            product_Name = "Adidas NMD R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "216dc317-0b19-4a65-bd0e-4e1a5fe95932",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Img1 = "StaticFiles/p-23/product-1.png",
                            product_Img2 = "StaticFiles/p-23/product-2.png",
                            product_Img3 = "StaticFiles/p-23/product-3.png",
                            product_Img4 = "StaticFiles/p-23/product-4.png",
                            product_Img5 = "StaticFiles/p-23/product-5.png",
                            product_Name = "Originals Unisex adidas",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "38ba1e10-fb63-4a19-984b-061b5b3e3f8b",
                            IsDelete = false,
                            product_CategoryId = "3f8c8a3b-0ab2-4e19-87b7-c3d89cd24e2d",
                            product_Description = "Adidas EQ19 Run H00933",
                            product_Img1 = "StaticFiles/p-24/product-1.png",
                            product_Img2 = "StaticFiles/p-24/product-2.png",
                            product_Img3 = "StaticFiles/p-24/product-3.png",
                            product_Img4 = "StaticFiles/p-24/product-4.png",
                            product_Img5 = "StaticFiles/p-24/product-5.png",
                            product_Name = "Adidas EQ19 Run H00933",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas EQ19 Run H00933",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "fcab161d-73e6-4617-b60d-190a002d50c3",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Img1 = "StaticFiles/p-25/product-1.png",
                            product_Img2 = "StaticFiles/p-25/product-2.png",
                            product_Img3 = "StaticFiles/p-25/product-3.png",
                            product_Img4 = "StaticFiles/p-25/product-4.png",
                            product_Img5 = "StaticFiles/p-25/product-5.png",
                            product_Name = "MLB Playball",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "3690f375-a3f0-42cc-9b53-9e29ae4f3bb1",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Img1 = "StaticFiles/p-26/product-1.png",
                            product_Img2 = "StaticFiles/p-26/product-2.png",
                            product_Img3 = "StaticFiles/p-26/product-3.png",
                            product_Img4 = "StaticFiles/p-26/product-4.png",
                            product_Img5 = "StaticFiles/p-26/product-5.png",
                            product_Name = "MLB Playball Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "4e07c925-1793-4c60-9a06-92cd484870d7",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Img1 = "StaticFiles/p-27/product-1.png",
                            product_Img2 = "StaticFiles/p-27/product-2.png",
                            product_Img3 = "StaticFiles/p-27/product-3.png",
                            product_Img4 = "StaticFiles/p-27/product-4.png",
                            product_Img5 = "StaticFiles/p-27/product-5.png",
                            product_Name = "MLB Playball Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "53aa7691-ef7c-4e29-9b57-360035eee347",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Img1 = "StaticFiles/p-28/product-1.png",
                            product_Img2 = "StaticFiles/p-28/product-2.png",
                            product_Img3 = "StaticFiles/p-28/product-3.png",
                            product_Img4 = "StaticFiles/p-28/product-4.png",
                            product_Img5 = "StaticFiles/p-28/product-5.png",
                            product_Name = "MLB Playball Origin Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "74756599-e683-4987-87dd-cb003d09dd31",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Img1 = "StaticFiles/p-29/product-1.png",
                            product_Img2 = "StaticFiles/p-29/product-2.png",
                            product_Img3 = "StaticFiles/p-29/product-3.png",
                            product_Img4 = "StaticFiles/p-29/product-4.png",
                            product_Img5 = "StaticFiles/p-29/product-5.png",
                            product_Name = "MLB Mule Playball",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "41dc43f6-b300-4c15-bda8-14fd283bb534",
                            IsDelete = false,
                            product_CategoryId = "70384946-c313-4edf-b98a-66ed223b2168",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Img1 = "StaticFiles/p-30/product-1.png",
                            product_Img2 = "StaticFiles/p-30/product-2.png",
                            product_Img3 = "StaticFiles/p-30/product-3.png",
                            product_Img4 = "StaticFiles/p-30/product-4.png",
                            product_Img5 = "StaticFiles/p-30/product-5.png",
                            product_Name = "MLB Mule Playball Fur",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.Property<string>("sip_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("sip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("sip_Id", "sip_ProductId");

                    b.HasIndex("sip_ProductId");

                    b.ToTable("SizeInProduct", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Property<string>("size_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("size_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("size_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("size_Id");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d5f3b54e-c721-4b91-8135-01a2e7191a92",
                            RoleId = "31bd0872-e289-4a8f-96fb-a0b7fc5bfb80"
                        },
                        new
                        {
                            UserId = "69420e08-6de1-4ffe-a733-f32ff388847b",
                            RoleId = "ecc2b10f-36a9-465b-90d6-e7a3ab3d4522"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.RolesTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("RolesTable");

                    b.HasData(
                        new
                        {
                            Id = "31bd0872-e289-4a8f-96fb-a0b7fc5bfb80",
                            ConcurrencyStamp = "990266ce-ea2b-494d-aebb-10ceeca3a9b1",
                            Name = "Admin",
                            NormalizedName = "admin",
                            IsDelete = false
                        },
                        new
                        {
                            Id = "ecc2b10f-36a9-465b-90d6-e7a3ab3d4522",
                            ConcurrencyStamp = "91f829b8-fe4c-499f-a51a-5a45f50e3eb9",
                            Name = "Staff",
                            NormalizedName = "staff",
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsersTable");

                    b.HasData(
                        new
                        {
                            Id = "d5f3b54e-c721-4b91-8135-01a2e7191a92",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5a675c82-b4d4-460d-bb71-6752e1ea8c7b",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECwG5tJVGQoRItGfzBgoJHZy7DmvLncF1FpiZD4F28SvjQ2C9ss2l/lP4EMPSrBVyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb7c7843-9549-41ed-8cae-b406509975ea",
                            TwoFactorEnabled = false,
                            UserName = "Staft",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        },
                        new
                        {
                            Id = "69420e08-6de1-4ffe-a733-f32ff388847b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adf341b5-b4a0-4a0d-b42a-16fa8dd78fce",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN7SA5jDKOz+2qsHCSmHdi0r2KmcV4H8Rzj7SDWk31buIjPpvVxZEFW+AItLetw3/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cb0471fa-a6bc-4770-a420-633586d9c3ca",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "userTable_UserId")
                        .WithMany("billsTablesList")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userTable_UserId");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ColorsTable", "cip_Color")
                        .WithMany("color_InProductsList")
                        .HasForeignKey("cip_ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "cip_Product")
                        .WithMany("product_colorInProductTablesList")
                        .HasForeignKey("cip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cip_Color");

                    b.Navigation("cip_Product");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "comment_ProductsTable")
                        .WithMany("product_CommentTableList")
                        .HasForeignKey("comment_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "comment_UsersTable")
                        .WithMany("CommentTableList")
                        .HasForeignKey("comment_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment_ProductsTable");

                    b.Navigation("comment_UsersTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.EmailCustomerTable", "contact_EmailCustomerTable")
                        .WithMany("emailC_ContactTableList")
                        .HasForeignKey("contact_EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contact_EmailCustomerTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.CategoriesTable", "product_CategoriesTable")
                        .WithMany("ProductsTableList")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_CategoriesTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.SizeTable", "sip_Size")
                        .WithMany("size_sizeInProductTablesList")
                        .HasForeignKey("sip_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "sip_Product")
                        .WithMany("product_sizeInProductTablesList")
                        .HasForeignKey("sip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sip_Product");

                    b.Navigation("sip_Size");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Navigation("ProductsTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Navigation("color_InProductsList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Navigation("emailC_ContactTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Navigation("product_CommentTableList");

                    b.Navigation("product_colorInProductTablesList");

                    b.Navigation("product_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Navigation("size_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.Navigation("CommentTableList");

                    b.Navigation("billsTablesList");
                });
#pragma warning restore 612, 618
        }
    }
}
