// <auto-generated />
using System;
using Fashion_Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fashion_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.Property<string>("bill_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("bill_Code")
                        .HasColumnType("int");

                    b.Property<DateTime>("bill_CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bill_IsConfirm")
                        .HasColumnType("bit");

                    b.Property<bool>("bill_IsPayment")
                        .HasColumnType("bit");

                    b.Property<double>("bill_Price")
                        .HasColumnType("float");

                    b.Property<string>("bill_ProductColorList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductPriceList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductSizeList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductUnitList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_ProductsIdList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bill_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("bill_Id");

                    b.HasIndex("bill_UserId");

                    b.ToTable("Bills", (string)null);

                    b.HasData(
                        new
                        {
                            bill_Id = "2784b4eb-f49e-4bec-834b-24c2333b9543",
                            CreateBy = "",
                            CreateOn = new DateTime(2023, 3, 23, 0, 20, 26, 408, DateTimeKind.Local).AddTicks(275),
                            IsDelete = false,
                            UpdateBy = "",
                            UpdateOn = new DateTime(2023, 3, 23, 0, 20, 26, 409, DateTimeKind.Local).AddTicks(547),
                            bill_Code = 1,
                            bill_CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bill_IsConfirm = false,
                            bill_IsPayment = false,
                            bill_Price = 0.0,
                            bill_ProductColorList = "Red|Black|Green|Yellow",
                            bill_ProductPriceList = "10|10|10|10|",
                            bill_ProductSizeList = "X|XL|S|M",
                            bill_ProductUnitList = "1|1|1|1|",
                            bill_ProductsIdList = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b|034b3077-7ce5-420c-a103-ea795aeb01b6|9ff292f3-1087-49d9-841c-d37c022da2e0|e6cf8556-de00-4c4f-9199-9504357ae64d|",
                            bill_UserId = "1fd3ca8a-9a44-4600-819c-804b6bd57b85"
                        },
                        new
                        {
                            bill_Id = "3f85fd19-d1aa-48f1-ac82-210151ecde1a",
                            CreateBy = "",
                            CreateOn = new DateTime(2023, 3, 23, 0, 20, 26, 408, DateTimeKind.Local).AddTicks(275),
                            IsDelete = false,
                            UpdateBy = "",
                            UpdateOn = new DateTime(2023, 3, 23, 0, 20, 26, 409, DateTimeKind.Local).AddTicks(547),
                            bill_Code = 1,
                            bill_CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bill_IsConfirm = false,
                            bill_IsPayment = false,
                            bill_Price = 0.0,
                            bill_ProductColorList = "Red|Black|Green|Yellow",
                            bill_ProductPriceList = "10|10|10|10|",
                            bill_ProductSizeList = "X|XL|S|M",
                            bill_ProductUnitList = "1|1|1|1|",
                            bill_ProductsIdList = "0b83fb38-7655-419e-bf7a-6da14af19b05|aaedc19f-219e-482f-8b55-b2a6ed29ae0a|d288e05b-9379-4743-9d0e-2d499e3c0065|98e2510d-d2b3-4582-b2a1-cf76399fd262|",
                            bill_UserId = "a8c43797-7bdb-40aa-aad8-311ad447e64b"
                        },
                        new
                        {
                            bill_Id = "2d3bbad9-70e7-4876-8c13-86c377567a1a",
                            CreateBy = "",
                            CreateOn = new DateTime(2023, 3, 23, 0, 20, 26, 408, DateTimeKind.Local).AddTicks(275),
                            IsDelete = false,
                            UpdateBy = "",
                            UpdateOn = new DateTime(2023, 3, 23, 0, 20, 26, 409, DateTimeKind.Local).AddTicks(547),
                            bill_Code = 1,
                            bill_CreateOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            bill_IsConfirm = false,
                            bill_IsPayment = false,
                            bill_Price = 0.0,
                            bill_ProductColorList = "Red|Black|Green|Yellow",
                            bill_ProductPriceList = "10|10|10|10|",
                            bill_ProductSizeList = "X|XL|S|M",
                            bill_ProductUnitList = "1|1|1|1|",
                            bill_ProductsIdList = "6f8a9897-c004-4beb-b37d-5e50a5800f87|030f0480-1ed4-4aaf-bbad-ec3e6d2f7b52|eb1b9845-fb95-49e0-8c14-c38fa59e340c|56e3ad0d-ee46-4d9b-a5ff-c3974fd3568c|",
                            bill_UserId = "6b181921-c620-4adc-8235-dfe9f1101f72"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Property<string>("category_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("category_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("category_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("category_Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            category_Id = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Jordan 1"
                        },
                        new
                        {
                            category_Id = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Air Force 1"
                        },
                        new
                        {
                            category_Id = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "Yeezy"
                        },
                        new
                        {
                            category_Id = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "NMD"
                        },
                        new
                        {
                            category_Id = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            IsDelete = false,
                            category_Description = "",
                            category_IsDelete = false,
                            category_Name = "For Her"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.Property<string>("cip_ColorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("cip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("cip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("cip_ColorId", "cip_ProductId");

                    b.HasIndex("cip_ProductId");

                    b.ToTable("ColorInProduct", (string)null);

                    b.HasData(
                        new
                        {
                            cip_ColorId = "bed3d69f-f5db-483f-926f-52992acc3c9a",
                            cip_ProductId = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b",
                            cip_IsDelete = false
                        },
                        new
                        {
                            cip_ColorId = "a6266efc-5930-4473-b9b9-4445cfe1dabd",
                            cip_ProductId = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b",
                            cip_IsDelete = false
                        },
                        new
                        {
                            cip_ColorId = "ffc841ff-ff76-413a-8f33-f4a6c85af330",
                            cip_ProductId = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b",
                            cip_IsDelete = false
                        },
                        new
                        {
                            cip_ColorId = "310eaf57-3ed1-427a-8684-66a1d18d480e",
                            cip_ProductId = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b",
                            cip_IsDelete = false
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Property<string>("color_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("color_IdDelete")
                        .HasColumnType("bit");

                    b.Property<string>("color_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("color_Id");

                    b.ToTable("Color", (string)null);

                    b.HasData(
                        new
                        {
                            color_Id = "bed3d69f-f5db-483f-926f-52992acc3c9a",
                            color_IdDelete = false,
                            color_Name = "Red"
                        },
                        new
                        {
                            color_Id = "a6266efc-5930-4473-b9b9-4445cfe1dabd",
                            color_IdDelete = false,
                            color_Name = "Black"
                        },
                        new
                        {
                            color_Id = "ffc841ff-ff76-413a-8f33-f4a6c85af330",
                            color_IdDelete = false,
                            color_Name = "Green"
                        },
                        new
                        {
                            color_Id = "310eaf57-3ed1-427a-8684-66a1d18d480e",
                            color_IdDelete = false,
                            color_Name = "Yellow"
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.Property<string>("comment_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("comment_ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("comment_Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comment_UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("comment_Id");

                    b.HasIndex("comment_ProductId");

                    b.HasIndex("comment_UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.Property<string>("contact_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("contact_EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("contact_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsCheck")
                        .HasColumnType("bit");

                    b.Property<string>("emailC_Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emailC_Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("contact_Id");

                    b.HasIndex("contact_EmailId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Property<string>("emailC_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("emailC_Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("emailC_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("emailC_Id");

                    b.ToTable("EmailCustomer", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Property<string>("product_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("product_CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("product_Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Img5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("product_Price")
                        .HasColumnType("float");

                    b.Property<int?>("product_Rate")
                        .HasColumnType("int");

                    b.Property<string>("product_ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_Sold")
                        .HasColumnType("int");

                    b.Property<string>("product_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("product_ViewNumber")
                        .HasColumnType("int");

                    b.HasKey("product_Id");

                    b.HasIndex("product_CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            product_Id = "b2f4a5b4-4a71-49a5-8288-fc144d2eed0b",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Low Elevate Low ‘Iced Lilac’ hiện đã có sẵn tại Sneaker Daily Shop, đừng bỏ lỡ cơ hội của mình nhé!",
                            product_Img1 = "StaticFiles/p-1/product-1.png",
                            product_Img2 = "StaticFiles/p-1/product-2.png",
                            product_Img3 = "StaticFiles/p-1/product-3.png",
                            product_Img4 = "StaticFiles/p-1/product-4.png",
                            product_Img5 = "StaticFiles/p-1/product-5.png",
                            product_Name = " Nike Air Jordan 1 Elevate",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low ‘Iced Lilac’ DH7004-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "034b3077-7ce5-420c-a103-ea795aeb01b6",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Img1 = "StaticFiles/p-2/product-1.png",
                            product_Img2 = "StaticFiles/p-2/product-2.png",
                            product_Img3 = "StaticFiles/p-2/product-3.png",
                            product_Img4 = "StaticFiles/p-2/product-4.png",
                            product_Img5 = "StaticFiles/p-2/product-5.png",
                            product_Name = "Nike Air Jordan 1 Elevate",
                            product_Price = 5290000.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Elevate Low Neutral Grey (Women’s) DH7004-110",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "9ff292f3-1087-49d9-841c-d37c022da2e0",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Img1 = "StaticFiles/p-3/product-1.png",
                            product_Img2 = "StaticFiles/p-3/product-2.png",
                            product_Img3 = "StaticFiles/p-3/product-3.png",
                            product_Img4 = "StaticFiles/p-3/product-4.png",
                            product_Img5 = "StaticFiles/p-3/product-5.png",
                            product_Name = "Nike Air Jordan 1 Retro",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Retro High 85 ‘Black White’ BQ4422-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "e6cf8556-de00-4c4f-9199-9504357ae64d",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Img1 = "StaticFiles/p-4/product-1.png",
                            product_Img2 = "StaticFiles/p-4/product-2.png",
                            product_Img3 = "StaticFiles/p-4/product-3.png",
                            product_Img4 = "StaticFiles/p-4/product-4.png",
                            product_Img5 = "StaticFiles/p-4/product-5.png",
                            product_Name = "Nike Air Jordan 1 Mid",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Mid SE ‘Coconut Milk’ DV1302-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "0b83fb38-7655-419e-bf7a-6da14af19b05",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Img1 = "StaticFiles/p-5/product-1.png",
                            product_Img2 = "StaticFiles/p-5/product-2.png",
                            product_Img3 = "StaticFiles/p-5/product-3.png",
                            product_Img4 = "StaticFiles/p-5/product-4.png",
                            product_Img5 = "StaticFiles/p-5/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Barely Grape’ (W) DC0774-501",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "aaedc19f-219e-482f-8b55-b2a6ed29ae0a",
                            IsDelete = false,
                            product_CategoryId = "480cf9fa-445a-4638-b75b-95a9d28b14d5",
                            product_Description = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Img1 = "StaticFiles/p-6/product-1.png",
                            product_Img2 = "StaticFiles/p-6/product-2.png",
                            product_Img3 = "StaticFiles/p-6/product-3.png",
                            product_Img4 = "StaticFiles/p-6/product-4.png",
                            product_Img5 = "StaticFiles/p-6/product-5.png",
                            product_Name = "Nike Air Jordan 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Jordan 1 Low ‘Desert’ (W) DC0774-201",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d288e05b-9379-4743-9d0e-2d499e3c0065",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Img1 = "StaticFiles/p-7/product-1.png",
                            product_Img2 = "StaticFiles/p-7/product-2.png",
                            product_Img3 = "StaticFiles/p-7/product-3.png",
                            product_Img4 = "StaticFiles/p-7/product-4.png",
                            product_Img5 = "StaticFiles/p-7/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Black Sail’ DV0794-001",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "98e2510d-d2b3-4582-b2a1-cf76399fd262",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Img1 = "StaticFiles/p-8/product-1.png",
                            product_Img2 = "StaticFiles/p-8/product-2.png",
                            product_Img3 = "StaticFiles/p-8/product-3.png",
                            product_Img4 = "StaticFiles/p-8/product-4.png",
                            product_Img5 = "StaticFiles/p-8/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LV8 ‘Sanddrift Sail’ DV0794-100",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "6f8a9897-c004-4beb-b37d-5e50a5800f87",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Img1 = "StaticFiles/p-9/product-1.png",
                            product_Img2 = "StaticFiles/p-9/product-2.png",
                            product_Img3 = "StaticFiles/p-9/product-3.png",
                            product_Img4 = "StaticFiles/p-9/product-4.png",
                            product_Img5 = "StaticFiles/p-9/product-5.png",
                            product_Name = "Nike Air Force 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Leopard’ CI0919-120",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "030f0480-1ed4-4aaf-bbad-ec3e6d2f7b52",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Img1 = "StaticFiles/p-10/product-1.png",
                            product_Img2 = "StaticFiles/p-10/product-2.png",
                            product_Img3 = "StaticFiles/p-10/product-3.png",
                            product_Img4 = "StaticFiles/p-10/product-4.png",
                            product_Img5 = "StaticFiles/p-10/product-5.png",
                            product_Name = "Nike Air Force 1 Low",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 Low Shadow ‘Summit White University Red Black’ DR7883-102",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "eb1b9845-fb95-49e0-8c14-c38fa59e340c",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Img1 = "StaticFiles/p-11/product-1.png",
                            product_Img2 = "StaticFiles/p-11/product-2.png",
                            product_Img3 = "StaticFiles/p-11/product-3.png",
                            product_Img4 = "StaticFiles/p-11/product-4.png",
                            product_Img5 = "StaticFiles/p-11/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 LX Leap High FD4622-131",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "56e3ad0d-ee46-4d9b-a5ff-c3974fd3568c",
                            IsDelete = false,
                            product_CategoryId = "a633ff4a-3536-4fad-b81a-5c6e175f4aca",
                            product_Description = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Img1 = "StaticFiles/p-12/product-1.png",
                            product_Img2 = "StaticFiles/p-12/product-2.png",
                            product_Img3 = "StaticFiles/p-12/product-3.png",
                            product_Img4 = "StaticFiles/p-12/product-4.png",
                            product_Img5 = "StaticFiles/p-12/product-5.png",
                            product_Name = "Nike Air Force 1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Nike Air Force 1 ’07 Retro Color Of The Month University Red White FD7039-600",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "97d75b09-2176-4eb2-8d39-f63f7421cf2a",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Img1 = "StaticFiles/p-13/product-1.png",
                            product_Img2 = "StaticFiles/p-13/product-2.png",
                            product_Img3 = "StaticFiles/p-13/product-3.png",
                            product_Img4 = "StaticFiles/p-13/product-4.png",
                            product_Img5 = "StaticFiles/p-13/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Onyx’ HQ4540",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "d6b3ed05-29e8-4290-9cc3-9c6b8403a795",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Img1 = "StaticFiles/p-14/product-1.png",
                            product_Img2 = "StaticFiles/p-14/product-2.png",
                            product_Img3 = "StaticFiles/p-14/product-3.png",
                            product_Img4 = "StaticFiles/p-14/product-4.png",
                            product_Img5 = "StaticFiles/p-14/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘MX Oat’ GW3773",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "387165a0-4f8c-4a61-a633-9122aaffe6be",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Img1 = "StaticFiles/p-15/product-1.png",
                            product_Img2 = "StaticFiles/p-15/product-2.png",
                            product_Img3 = "StaticFiles/p-15/product-3.png",
                            product_Img4 = "StaticFiles/p-15/product-4.png",
                            product_Img5 = "StaticFiles/p-15/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 Sesame F99710",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "efd55c12-1e69-4153-86c4-db283a2e35b2",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Img1 = "StaticFiles/p-16/product-1.png",
                            product_Img2 = "StaticFiles/p-16/product-2.png",
                            product_Img3 = "StaticFiles/p-16/product-3.png",
                            product_Img4 = "StaticFiles/p-16/product-4.png",
                            product_Img5 = "StaticFiles/p-16/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Salt’ HQ2060",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "84860176-0c20-493a-b754-564d80908858",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Img1 = "StaticFiles/p-17/product-1.png",
                            product_Img2 = "StaticFiles/p-17/product-2.png",
                            product_Img3 = "StaticFiles/p-17/product-3.png",
                            product_Img4 = "StaticFiles/p-17/product-4.png",
                            product_Img5 = "StaticFiles/p-17/product-5.png",
                            product_Name = "Adidas Originals Yeezy",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Originals Yeezy Foam Runner ‘Stone Sage’ GX4472",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "59c64d19-17fe-4f74-8820-064b08509842",
                            IsDelete = false,
                            product_CategoryId = "3e3c32ce-9fdf-4593-a0e8-853258c2e02a",
                            product_Description = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Img1 = "StaticFiles/p-18/product-1.png",
                            product_Img2 = "StaticFiles/p-18/product-2.png",
                            product_Img3 = "StaticFiles/p-18/product-3.png",
                            product_Img4 = "StaticFiles/p-18/product-4.png",
                            product_Img5 = "StaticFiles/p-18/product-5.png",
                            product_Name = "Adidas Yeezy Boost 350",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas Yeezy Boost 350 V2 ‘Core Black Red’ BY9612",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "8068924e-9800-430e-9565-29fa5f87648b",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Img1 = "StaticFiles/p-19/product-1.png",
                            product_Img2 = "StaticFiles/p-19/product-2.png",
                            product_Img3 = "StaticFiles/p-19/product-3.png",
                            product_Img4 = "StaticFiles/p-19/product-4.png",
                            product_Img5 = "StaticFiles/p-19/product-5.png",
                            product_Name = "Adidas NMD_R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD_R1 ‘Black Solar Red’ GZ9274",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "82eb1194-49a4-4387-aae1-6b033f4d1060",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Img1 = "StaticFiles/p-20/product-1.png",
                            product_Img2 = "StaticFiles/p-20/product-2.png",
                            product_Img3 = "StaticFiles/p-20/product-3.png",
                            product_Img4 = "StaticFiles/p-20/product-4.png",
                            product_Img5 = "StaticFiles/p-20/product-5.png",
                            product_Name = "Adidas BOSSK NMD_R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas BOSSK NMD_R1 SPECTOO ‘Black Yellow’ GX6792",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "bbbad47c-0cef-4827-aa77-ca653828c1b9",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Img1 = "StaticFiles/p-21/product-1.png",
                            product_Img2 = "StaticFiles/p-21/product-2.png",
                            product_Img3 = "StaticFiles/p-21/product-3.png",
                            product_Img4 = "StaticFiles/p-21/product-4.png",
                            product_Img5 = "StaticFiles/p-21/product-5.png",
                            product_Name = "Adidas NMD R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 ‘Off White Sand’ FV1793",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "c61362a0-fe0f-4306-ab2c-b6b45cfeeb38",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Img1 = "StaticFiles/p-22/product-1.png",
                            product_Img2 = "StaticFiles/p-22/product-2.png",
                            product_Img3 = "StaticFiles/p-22/product-3.png",
                            product_Img4 = "StaticFiles/p-22/product-4.png",
                            product_Img5 = "StaticFiles/p-22/product-5.png",
                            product_Name = "Adidas NMD R1",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas NMD R1 Pixar ‘Black’ GX0997",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "51737ad4-cc97-4e26-86fd-08524731e243",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Img1 = "StaticFiles/p-23/product-1.png",
                            product_Img2 = "StaticFiles/p-23/product-2.png",
                            product_Img3 = "StaticFiles/p-23/product-3.png",
                            product_Img4 = "StaticFiles/p-23/product-4.png",
                            product_Img5 = "StaticFiles/p-23/product-5.png",
                            product_Name = "Originals Unisex adidas",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Originals Unisex adidas Nmd R1 ‘Cloud White’ GX0996",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "6f1a4ab3-773b-4eda-9be8-04758f4a59b1",
                            IsDelete = false,
                            product_CategoryId = "798decc8-17c8-4152-9652-61e55d5f5cce",
                            product_Description = "Adidas EQ19 Run H00933",
                            product_Img1 = "StaticFiles/p-24/product-1.png",
                            product_Img2 = "StaticFiles/p-24/product-2.png",
                            product_Img3 = "StaticFiles/p-24/product-3.png",
                            product_Img4 = "StaticFiles/p-24/product-4.png",
                            product_Img5 = "StaticFiles/p-24/product-5.png",
                            product_Name = "Adidas EQ19 Run H00933",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "Adidas EQ19 Run H00933",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "84aef9e1-27be-4c34-ad38-699ee22595dc",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Img1 = "StaticFiles/p-25/product-1.png",
                            product_Img2 = "StaticFiles/p-25/product-2.png",
                            product_Img3 = "StaticFiles/p-25/product-3.png",
                            product_Img4 = "StaticFiles/p-25/product-4.png",
                            product_Img5 = "StaticFiles/p-25/product-5.png",
                            product_Name = "MLB Playball",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Black’ 3AMUMDA2N-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "6e19f645-cdd0-4ffd-bc30-c8c17f01178b",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Img1 = "StaticFiles/p-26/product-1.png",
                            product_Img2 = "StaticFiles/p-26/product-2.png",
                            product_Img3 = "StaticFiles/p-26/product-3.png",
                            product_Img4 = "StaticFiles/p-26/product-4.png",
                            product_Img5 = "StaticFiles/p-26/product-5.png",
                            product_Name = "MLB Playball Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Beige’ 3AMUMDA2N-50BGS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "9690b826-043a-4168-9326-dcf01b789fd9",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Img1 = "StaticFiles/p-27/product-1.png",
                            product_Img2 = "StaticFiles/p-27/product-2.png",
                            product_Img3 = "StaticFiles/p-27/product-3.png",
                            product_Img4 = "StaticFiles/p-27/product-4.png",
                            product_Img5 = "StaticFiles/p-27/product-5.png",
                            product_Name = "MLB Playball Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Mule Dia Monogram New York Yankees ‘Cream’ 3AMUM212N-50BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "b27dbbf8-c6bf-4a0f-ad86-5b99b94e03be",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Img1 = "StaticFiles/p-28/product-1.png",
                            product_Img2 = "StaticFiles/p-28/product-2.png",
                            product_Img3 = "StaticFiles/p-28/product-3.png",
                            product_Img4 = "StaticFiles/p-28/product-4.png",
                            product_Img5 = "StaticFiles/p-28/product-5.png",
                            product_Name = "MLB Playball Origin Mule",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Playball Origin Mule New York Yankees Black 32SHS1111-50L",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "b92050ff-1fbd-4cc1-88af-ddbc1d69866d",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Img1 = "StaticFiles/p-29/product-1.png",
                            product_Img2 = "StaticFiles/p-29/product-2.png",
                            product_Img3 = "StaticFiles/p-29/product-3.png",
                            product_Img4 = "StaticFiles/p-29/product-4.png",
                            product_Img5 = "StaticFiles/p-29/product-5.png",
                            product_Name = "MLB Mule Playball",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram New York Yankees Black 3AMUUFS26-50BKS",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        },
                        new
                        {
                            product_Id = "98cbcb02-246e-42b3-a377-a61f85ccb015",
                            IsDelete = false,
                            product_CategoryId = "736dfef6-8baa-434a-b295-e6a3c8e8c898",
                            product_Description = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Img1 = "StaticFiles/p-30/product-1.png",
                            product_Img2 = "StaticFiles/p-30/product-2.png",
                            product_Img3 = "StaticFiles/p-30/product-3.png",
                            product_Img4 = "StaticFiles/p-30/product-4.png",
                            product_Img5 = "StaticFiles/p-30/product-5.png",
                            product_Name = "MLB Mule Playball Fur",
                            product_Price = 10.0,
                            product_Rate = 4,
                            product_ShortDescription = "MLB Mule Playball Fur Diamond Monogram Boston Red Sox D.Beige 3AMUUFS26-43BGD",
                            product_Sold = 10,
                            product_Type = "Type1",
                            product_ViewNumber = 10
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.Property<string>("sip_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sip_ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("sip_IsDelete")
                        .HasColumnType("bit");

                    b.HasKey("sip_Id", "sip_ProductId");

                    b.HasIndex("sip_ProductId");

                    b.ToTable("SizeInProduct", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Property<string>("size_Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("size_IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("size_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("size_Id");

                    b.ToTable("Size", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1fd3ca8a-9a44-4600-819c-804b6bd57b85",
                            RoleId = "c4669085-8d1d-42e2-9dc3-c37cea478060"
                        },
                        new
                        {
                            UserId = "a8c43797-7bdb-40aa-aad8-311ad447e64b",
                            RoleId = "796fc75d-47ad-4186-b58e-7bfa954942c4"
                        },
                        new
                        {
                            UserId = "6b181921-c620-4adc-8235-dfe9f1101f72",
                            RoleId = "c4669085-8d1d-42e2-9dc3-c37cea478060"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.RolesTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("RolesTable");

                    b.HasData(
                        new
                        {
                            Id = "c4669085-8d1d-42e2-9dc3-c37cea478060",
                            ConcurrencyStamp = "f56d0f38-1b2b-4153-84ab-6e9d5b4cf4a5",
                            Name = "Admin",
                            NormalizedName = "admin",
                            IsDelete = false
                        },
                        new
                        {
                            Id = "796fc75d-47ad-4186-b58e-7bfa954942c4",
                            ConcurrencyStamp = "cf6ab091-6f65-45d2-a0f9-88a595c48303",
                            Name = "Staff",
                            NormalizedName = "staff",
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("UsersTable");

                    b.HasData(
                        new
                        {
                            Id = "1fd3ca8a-9a44-4600-819c-804b6bd57b85",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a66692d4-18d1-45ef-b011-c3bf8e017ae0",
                            Email = "staff@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@GMAIL.COM",
                            NormalizedUserName = "STAFF@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBT4oD4wzygk2gwIvuznJnPyw43A++Q/JzwK6B3sSG5q4i0DDT9BOUpi4IPm9fhFMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8e57601-cb56-4e8e-93ec-00bc6bf53eab",
                            TwoFactorEnabled = false,
                            UserName = "Staff",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        },
                        new
                        {
                            Id = "a8c43797-7bdb-40aa-aad8-311ad447e64b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bbaa70d6-cd0f-4d34-8627-07dea345d8e2",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHdztSxoYW7McWUumOHU6L88qM0Mmb6vlxhXVwBrkbQd13x1SSoHelNRw639Vq3JDw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d889eec7-dd5e-4cdd-b5b7-3674a10cc40f",
                            TwoFactorEnabled = false,
                            UserName = "Admin",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        },
                        new
                        {
                            Id = "6b181921-c620-4adc-8235-dfe9f1101f72",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9c31f342-71da-489c-b3e9-da4ddf0518d8",
                            Email = "staff2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF2@GMAIL.COM",
                            NormalizedUserName = "STAFF2@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBcUPL9v9wdBEej0T0xFACRM+WnTZGygPqOqwkFNUV9XR6LmbXSaLhO9cGP7fq8joA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "932271e0-df8a-4e13-a9b0-b262381ba8fe",
                            TwoFactorEnabled = false,
                            UserName = "Staff2",
                            Address = "",
                            FirstName = "",
                            IsDelete = false,
                            LastName = ""
                        });
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.BillsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "userTable_UserId")
                        .WithMany("billsTablesList")
                        .HasForeignKey("bill_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userTable_UserId");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ColorsTable", "cip_Color")
                        .WithMany("color_InProductsList")
                        .HasForeignKey("cip_ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "cip_Product")
                        .WithMany("product_colorInProductTablesList")
                        .HasForeignKey("cip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cip_Color");

                    b.Navigation("cip_Product");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CommentTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "comment_ProductsTable")
                        .WithMany("product_CommentTableList")
                        .HasForeignKey("comment_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.UsersTable", "comment_UsersTable")
                        .WithMany("CommentTableList")
                        .HasForeignKey("comment_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("comment_ProductsTable");

                    b.Navigation("comment_UsersTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ContactTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.EmailCustomerTable", "contact_EmailCustomerTable")
                        .WithMany("emailC_ContactTableList")
                        .HasForeignKey("contact_EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("contact_EmailCustomerTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.CategoriesTable", "product_CategoriesTable")
                        .WithMany("ProductsTableList")
                        .HasForeignKey("product_CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product_CategoriesTable");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeInProductTable", b =>
                {
                    b.HasOne("Fashion_Infrastructure.Entities.SizeTable", "sip_Size")
                        .WithMany("size_sizeInProductTablesList")
                        .HasForeignKey("sip_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fashion_Infrastructure.Entities.ProductsTable", "sip_Product")
                        .WithMany("product_sizeInProductTablesList")
                        .HasForeignKey("sip_ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sip_Product");

                    b.Navigation("sip_Size");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.CategoriesTable", b =>
                {
                    b.Navigation("ProductsTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ColorsTable", b =>
                {
                    b.Navigation("color_InProductsList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.EmailCustomerTable", b =>
                {
                    b.Navigation("emailC_ContactTableList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.ProductsTable", b =>
                {
                    b.Navigation("product_CommentTableList");

                    b.Navigation("product_colorInProductTablesList");

                    b.Navigation("product_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.SizeTable", b =>
                {
                    b.Navigation("size_sizeInProductTablesList");
                });

            modelBuilder.Entity("Fashion_Infrastructure.Entities.UsersTable", b =>
                {
                    b.Navigation("CommentTableList");

                    b.Navigation("billsTablesList");
                });
#pragma warning restore 612, 618
        }
    }
}
